name: Build e Push para o Docker Hub

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extrair a versão da tag
        id: tag
        run: |
          # Extrai a versão da tag (remove o 'v' inicial)
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version: $VERSION"

      - name: Configurar o Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Entrar no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir e enviar a imagem do Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/devtracker:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/devtracker:${{ steps.tag.outputs.VERSION }}
